name: ayol_uchun
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  go_router: ^15.1.2
  flutter_localization: ^0.3.2
  dio: ^5.8.0+1
  hive: ^2.2.3
  connectivity_plus: ^6.1.4
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5
  flutter_localizations:
    sdk: flutter
  pinput: ^5.0.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  path_provider: ^2.1.5
  json_serializable: ^6.9.5
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: SFPro
      fonts:
        - asset: fonts/sf_pro/SF-PRO-DISPLAY-REGULAR.OTF
          weight: 400
        - asset: fonts/sf_pro/SF-PRO-DISPLAY-MEDIUM.OTF
          weight: 500
        - asset: fonts/sf_pro/SF-PRO-DISPLAY-SEMIBOLD.OTF
          weight: 600
        - asset: fonts/sf_pro/SF-PRO-DISPLAY-BOLD.OTF
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/for_women.png"
  uses-material-design: true


